source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'XMPPMessenger_Example', :exclusive => true do
  pod "XMPPMessenger", :path => "../"
	pod "FMDP"
	pod "JSQMessagesViewController"
	pod "JSQSystemSoundPlayer"
end

target 'XMPPMessenger_Tests', :exclusive => true do
  pod "XMPPMessenger", :path => "../"

  
end
