source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
silent_warnings!

target 'xmpp-messenger-ios_Example', :exclusive => true do
  pod "xmpp-messenger-ios", :path => "../"
	pod "JSQSystemSoundPlayer"
	pod "JSQMessagesViewController"
	pod "XMPPFramework"
	pod "FMDB"
end

target 'xmpp-messenger-ios_Tests', :exclusive => true do
  pod "xmpp-messenger-ios", :path => "../"
	pod "JSQSystemSoundPlayer"
	pod "JSQMessagesViewController"
	pod "XMPPFramework"
	pod "FMDB"
end
